### ISSUE TITLE
multibib extension installed but not found during render

### ISSUE THREAD

**Issue by rolandknapp** [pandoc-ext/multibib#11]
I am experiencing a similar issue to the one I encountered previously (and resolved) when using the section-bibliographies filter [(link to description of section-bibliographies issue)](https://stackoverflow.com/questions/75632573/quarto-extension-installed-but-not-found-during-render). That is, using RStudio/Quarto I installed the `multibib` extension and added `multibib` to the filters entry in the document's YAML header. When I render the document (to PDF), I get the error message, "Error running filter multibib: Could not find executable multibib". I then added the full relative path for `multibib.lua` to the `multibib` filter entry (`/_extensions/pandoc-ext/multibib/multibib.lua`). That errors with the message, "Error running filter /_extensions/pandoc-ext/multibib/multibib.lua: cannot open /_extensions/pandoc-ext/multibib/multibib.lua: No such file or directory." Using the full absolute file path produces the same error message. I have confirmed that `multibib.lua` is present in the referenced directory. The relevant portion of the YAML is as follows: 
```
bibliography: 
  main: translocation.bib
  supporting: supporting_info.bib
filters: 
  - multibib
validate-yaml: false
csl: pnas.csl
format: pdf
```
Do you have any suggestions on how to resolve this? 

Environment: Quarto 1.2.335, RStudio 2023.09.1+494, OS Ubuntu 22.04.3 LTS
