### ISSUE TITLE
Empty bibliographies with Quarto website

### ISSUE THREAD

**Issue by dpo** [pandoc-ext/multibib#16]
I'm trying to write a Quarto website and use this filter to produce a list of publications. I tried to follow the `README`, and must be doing something wrong because the bibliographies aren't rendered at all in the html output. Quarto doesn't output any particular error message. I installed this filter with `quarto install extension pandoc-ext/multibib`.

In `_quarto.yml`, I have
```
project:
  type: website

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd

filters:
  - multibib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```

I'm not using any other filter.

In `publications.qmd`, I'm testing the filter with

```
---
title: "Publications"
bibliography:
    articles2020: articles2020.bib
    articles2019: articles2019.bib
validate-yaml: false
---

## 2020

::: {#refs-articles2020}
:::

## 2019

::: {#refs-articles2019}
:::
```

When the html is rendered, the sections "2020" and "2019" of the publications page are empty. What am I doing wrong?

**Comment by tarleb** [comment]
I believe that Quarto has changed the order in which filters and the citeproc citation processing tool are run, but I didn't have time yet to look into that. Maybe try to set `citeproc: false`.

**Comment by dpo** [comment]
Thank you for the quick reply. No luck with `citeproc: false` (I tried putting it in `_quarto.yml` and in `publications.qmd` as it's never clear to me where it should go).

**Comment by tarleb** [comment]
Thanks for checking. I'll have a look, but it might take a while, as I'm more time constrained than usual right now.

**Comment by dpo** [comment]
It may not be a Quarto issue. If I use `publications.qmd` above (with or without `validate-yaml: false`) and run
```bash
pandoc --lua-filter _extensions/pandoc-ext/multibib/multibib.lua publications.qmd -t markdown
```
from the command line, I get
```
[WARNING] Could not deduce format from file extension .qmd
  Defaulting to markdown

## 2020

### Journal Articles

::: {#refs-articles2020}
:::

## 2019

### Journal Articles

::: {#refs-articles2019}
:::
```
I must be doing something wrong?!

**Comment by dpo** [comment]
As I suspected, the problem was between the chair and the monitor. I forgot to add `nocite: "[@*]"` to my yaml header:
```yaml
---
title: "Publications"
bibliography:
    articles2020: articles2020.bib
    articles2019: articles2019.bib
validate-yaml: false
nocite: "[@*]"  # <---
---
```
Sorry for the noise, and thank you for a great extension!!!
