### ISSUE TITLE
Adapting to quarto book 

### ISSUE THREAD

**Issue by jpatteet** [pandoc-ext/multibib#5]
Hi, 
I was wondering if that could be used in quarto for books (PDF) . The idea would be to have a refernce section for each chapter of my book that has a reference section in their qmd file.

I tried the following as a _quarto.yml file but it does not work
```

project:
  type: book

book:
  title: "Test"
  author: "name"
  date: "15.06.2023"

  chapters:
    - index.qmd
    - part: "part1"
      chapters: 
        - Article1.qmd
        - Article2.qmd
    - part: "part2"
       chapters:
          - Chapter1.qmd
          

filters: 
  - multibib
bibliography: 
  Art1: refArt1.bib
  Art2: refArt2.bib
  
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  
editor: visual
```
In Article1.qmd I have a reference section 
```

## References {.unnumbered}

::: {#refs-Art1}
:::
```
and the same principle in Article2.qmd.

Any idea how this would be possible or what I could try next ?
